# Generated by Django 4.2.4 on 2023-08-26 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255)),
                ('icon', models.ImageField(upload_to='category/icons/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название факультета')),
                ('hard_or_easy', models.CharField(choices=[('easy', 'Легкий'), ('hard', 'Тяжело')], max_length=10, verbose_name='Легко или сложно')),
                ('popularity', models.BooleanField(default=False, verbose_name='Популярный факультет')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', localflavor.us.models.USStateField(max_length=2)),
                ('type', models.CharField(choices=[('private', 'Частный'), ('public', 'Государственный')], max_length=100, verbose_name='Тип университета')),
                ('dorm', models.BooleanField(default=False, verbose_name='Жилые помещения')),
                ('price_out', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('cost_of_living', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя цена')),
                ('majors', models.ManyToManyField(related_name='university', to='information.major')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_grades', models.CharField(max_length=50, verbose_name='Тип оценок')),
                ('applicant_competition', models.CharField(max_length=70, verbose_name='Конкуренция')),
                ('sat_range', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SAT результаты')),
                ('ielts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IELTS результаты')),
                ('acceptance_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент зачисления')),
                ('avg_gpa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GPA')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('uni_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='information.university')),
            ],
        ),
    ]
