# Generated by Django 4.2.4 on 2023-08-26 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='applicant_competition',
            field=models.CharField(choices=[('easy', 'Легко'), ('normal', 'Нормальны'), ('high', 'Высокий'), ('extreme_high', 'Очень высокая')], max_length=20, verbose_name='Конкуренция'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='avg_gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(4.0)], verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ielts',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(9.0)], verbose_name='IELTS результаты'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='sat_range',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1600)], verbose_name='SAT результаты'),
        ),
    ]
