# Generated by Django 4.2.4 on 2023-08-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_admission_applicant_competition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='university',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='applicant_competition',
            field=models.CharField(choices=[('easy', 'Легко'), ('normal', 'Нормальный'), ('high', 'Высокий'), ('extreme_high', 'Очень высокая')], max_length=20, verbose_name='Конкуренция'),
        ),
    ]
