# Generated by Django 4.2.4 on 2023-08-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_about_university_latitude_university_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='icon',
            field=models.ImageField(default='location/default_icon.png', upload_to='university/icons/', verbose_name='Иконка'),
        ),
    ]
