# Generated by Django 4.2.4 on 2023-08-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_university_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='detail',
            field=models.TextField(default='Подробная информация о нашем университете будет доступна здесь.', verbose_name='Рассказ об университете'),
        ),
    ]
