# Generated by Django 4.2.4 on 2023-08-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_university_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.ImageField(default='location/default_image.png', upload_to='university/images/', verbose_name='Фото'),
        ),
    ]
