# Generated by Django 4.2.4 on 2023-08-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_university_professor_university_text_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='university',
            name='text_p',
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=255, verbose_name='Название')),
                ('last_name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Подробная информация о профессоре будет доступна здесь.', verbose_name='Информация об профессоре')),
                ('degree', models.TextField(default='Здесь степень профессора', verbose_name='Какая степень')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='information.university')),
            ],
        ),
    ]
