# Generated by Django 4.2.4 on 2023-09-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0010_alter_universityrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityrating',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
