# Generated by Django 4.2.4 on 2023-09-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_alter_universityrating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='amina/images/', verbose_name='Фото')),
            ],
        ),
    ]
