# Generated by Django 4.2.4 on 2023-09-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_amina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
