# Generated by Django 4.2.4 on 2023-09-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
