# Generated by Django 4.2.4 on 2023-09-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0019_university_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='popularity',
        ),
    ]
