# Generated by Django 4.2.4 on 2023-09-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0021_major_description_major_img_major_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Название')),
                ('last_name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Подробная информация об известном человеке будет доступна здесь.', verbose_name='Информация об известном человеке')),
                ('action', models.TextField(default='Подробная информация об известном человеке будет доступна здесь', verbose_name='Знаменитые их действия в сторону этой профессии')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='famous', to='information.major')),
            ],
        ),
    ]
