# Generated by Django 4.2.4 on 2023-09-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0022_famouspeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='famouspeople',
            name='image',
            field=models.ImageField(default='location/default_image.png', upload_to='majors/images', verbose_name='Фото'),
        ),
    ]
