# Generated by Django 4.2.4 on 2026-03-01 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0025_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='theme_color',
            field=models.CharField(blank=True, default='#722F37', help_text="Hex color for this university's detail page (e.g. #722F37 burgundy, #0f766e teal).", max_length=7, verbose_name='Theme color (hex)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='acceptance_rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Acceptance rate'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='applicant_competition',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('high', 'High'), ('extreme_high', 'Very high')], max_length=20, verbose_name='Competition'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ielts',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(9.0)], verbose_name='IELTS score'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='sat_range',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1600)], verbose_name='SAT score'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='type_of_grades',
            field=models.CharField(max_length=50, verbose_name='Grade type'),
        ),
        migrations.AlterField(
            model_name='amina',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='amina/images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='famouspeople',
            name='action',
            field=models.TextField(default='Detailed information will be available here.', verbose_name='Notable actions in this field'),
        ),
        migrations.AlterField(
            model_name='famouspeople',
            name='description',
            field=models.TextField(default='Detailed information will be available here.', verbose_name='Information about this person'),
        ),
        migrations.AlterField(
            model_name='famouspeople',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='famouspeople',
            name='image',
            field=models.ImageField(default='location/default_image.png', upload_to='majors/images', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='famouspeople',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='major',
            name='description',
            field=models.TextField(default='Information about the major', null=True, verbose_name='Major description'),
        ),
        migrations.AlterField(
            model_name='major',
            name='hard_or_easy',
            field=models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], max_length=10, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='major',
            name='img',
            field=models.ImageField(default='location/default_image.png', upload_to='majors/images', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Major name'),
        ),
        migrations.AlterField(
            model_name='major',
            name='popularity',
            field=models.BooleanField(default=False, verbose_name='Popular major'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='degree',
            field=models.TextField(default='Professor degree information', verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='description',
            field=models.TextField(default='Detailed information about the professor will be available here.', verbose_name='Professor information'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='fist_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='cost_of_living',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Average cost'),
        ),
        migrations.AlterField(
            model_name='university',
            name='detail',
            field=models.TextField(default='Detailed information about our university will be available here.', verbose_name='University story'),
        ),
        migrations.AlterField(
            model_name='university',
            name='dorm',
            field=models.BooleanField(default=False, verbose_name='Dormitory'),
        ),
        migrations.AlterField(
            model_name='university',
            name='icon',
            field=models.ImageField(default='location/default_icon.png', upload_to='university/icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(default='location/default_image.png', upload_to='university/images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='university',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='university',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='price_out',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=100, verbose_name='University type'),
        ),
    ]
